### ISSUE TITLE
"base" pattern, can I use named parameters?

### ISSUE THREAD

**Issue by frederikhors** [lukeed/navaid#14]
Coming from this example: https://codesandbox.io/s/reverent-tesla-c0kq0, if I'm not wrong it seems Navaid doesn't understand the below code:

```js
const router = Navaid("/team/:teamID")
    .on("", obj => draw(PagePlayersList, obj))
    ...
```

It seems it doesn't work.

Is the `base` path in `Navaid("/team/:teamID")` correct? Can I use named parameters like `:teamID`?

**Comment by lukeed** [comment]
it doesn't and won't ever work. A `base` is static
