### ISSUE TITLE
Render something during route import().

### ISSUE THREAD

**Issue by frederikhors** [lukeed/navaid#16]
Thanks to https://github.com/lukeed/svelte-demo I'm learning how to use the amazing `navaid`.

I have a doubt: how can I render something (eg. "Loading...") until `import(ing)()` a Route?

**Example**:

```js
const router = Navaid('/')
  .on('/', () => import('../routes/Home.svelte').then(draw))
  .on('/about', () => import('../routes/About.svelte').then(draw))
  .on('/blog', () => import('../routes/Blog.svelte').then(draw))
  .on('/blog/:title', obj => import('../routes/Article.svelte').then(m => draw(m, obj)))
  .listen();
```

Let's say `import('../routes/About.svelte')`is slow, the browser is waiting but nothing is showed to the user.

Am I wrong?

**Comment by frederikhors** [comment]
**REPRODUCTION**:

https://codesandbox.io/s/github/lukeed/svelte-demo

**Comment by lukeed** [comment]
Import() is just a promise, so you'll want to do something before the promise begins and then reset/cleanup once it resolves.

On phone and so I can't look at repro now, but this basic structure works for _anything_ asynchronous

```js
loading = true;
fetch(something).then(r => json ()).then(data => {
  loading = false;
  // handle data
})
```

This is also not a navaid issue nor its concern

**Comment by lukeed** [comment]
Here's one way you could solve it with Svelte: https://codesandbox.io/s/svelte-demo-mqxy7

Since `Route` is the thing/page being displace, you just put something there as a placeholder (for this issue, at least).

Hope that helps~
