### ISSUE TITLE
Best approach to implement protect and public routes

### ISSUE THREAD

**Issue by DesdeChaves** [lukeed/navaid#22]
what is this the best practice to implement a separation between public and protected routes?

I know that is possible to implement this kind of separation inside a protected components. For example, if the user is not authenticated I can call the route /login. 

Are there another approach?

**Comment by lukeed** [comment]
Hey,

You'd just lead with that authentication logic at the beginning of each route handler that you want to care. It just requires that you store that User data elsewhere and have access to it.

Here's a [simplified demo](https://codesandbox.io/s/elegant-austin-5tye6) using multiple routers. There other ways to do it – you also don't need to have multiple routers to accomplish this. It's just one example.

Hope that helps~!
