### ISSUE TITLE
Scroll to top after route()?

### ISSUE THREAD

**Issue by frederikhors** [lukeed/navaid#23]
What about scroll to top routing on new pages?

**Comment by lukeed** [comment]
Hey, no - navaid doesn't care. That is part of your handler function. And more specifically, this should be part of your Svelte component lifecycle, since it's there that a "mount" is known.

Navaid is _just_ a router. "On this URL pattern, run this function"

**Comment by frederikhors** [comment]
Thanks for your answer as usual.

I think on project https://github.com/lukeed/svelte-demo it would be amazing an example of what you mean.

**Comment by lukeed** [comment]
Sure! If you open a ticket there I'll get to it

**Comment by frederikhors** [comment]
https://github.com/lukeed/svelte-demo/issues/6
