### ISSUE TITLE
Consider support for hash-based routing

### ISSUE THREAD

**Issue by TJKoury** [lukeed/navaid#27]
For SPA's that need to work regardless of hosting environment, using hash-based navigation is usually the best solution, especially if link-sharing is integral to the app.

I made these small changes to enable hash support:

```
if ((uri = fmt(uri || location.href.replace(location.origin, "")))) {
//uri = uri.match(/[^\?#]*/)[0];
```
and
```
...
		addEventListener("click", click);
		addEventListener("hashChange", run);
		$.unlisten = function() {
...
			removeEventListener("click", click);
			removeEventListener("hashChange", run);
		};
```
Given the regex I assume you did not want support for hashes in this library, but happy to write a test and submit a pull if you are open to it.

**Comment by paulocoghi** [comment]
Just out of curiosity, in which hosting environments would hash-based navigation be better? _(genuine question)_

**Comment by TJKoury** [comment]
@paulocoghi Websites where the back end does not do server-side rendering, or serve the same SPA for every route past a certain root.

For example, if my root path is `https://site.com/documentation` and I want a template at 'https://site.com/documentation/page1', and I'm on a hosting platform that won't let me edit routes to always serve the index.html at `/documentation`, then I cannot use that path directly (bookmark, sharing, etc).

**Comment by paulocoghi** [comment]
Thanks for the clarification. I asked this because I am not much in favor of hash-based, but I understand that this situation may not be so uncommon.

I personally have never had a problem with not using hash-based routing (only "normal" routing on all my projects), but my scenario can be somewhat limited.

**Comment by AlexGalays** [comment]
it would defeat the purpose of this lib: offering a working, albeit simple routing solution at a very small size.

**Comment by peteringram0** [comment]
Im surprised this lib doesn't seem to support hash based routing. If using live updating or similar in development environment this is really useful. Is there anything that can be done to support this?

**Comment by AlexGalays** [comment]
> Im surprised this lib doesn't seem to support hash based routing. If using live updating or similar in development environment this is really useful. Is there anything that can be done to support this?

You can do live updating even with push based routing though.

**Comment by paulocoghi** [comment]
> > Im surprised this lib doesn't seem to support hash based routing. If using live updating or similar in development environment this is really useful. Is there anything that can be done to support this?
> 
> You can do live updating even with push based routing though.

Exactly. You must configure your live-reload library/environment to be compatible with SPA's.
