### ISSUE TITLE
commonjs build does not have same exports as esm build

### ISSUE THREAD

**Issue by larrybotha** [lukeed/navaid#29]
Ran into this while writing tests.

The bundled script contains `dist/navaid.mjs`, while Jest (or more accurately node?) imports `dist/navaid.js`.

- `navaid.mjs` exports `Navaid` as the default export
  - Rollup imports this file (can't speak for other bundlers, but I imagine the behaviour is the same)
- `navaid.js` exports `Navaid` as a named export
  - when Jest comes across `import navaid from "navaid"` it imports this file
  - this results in `navaid === undefined`, since there is no default export

Thought I'd bring it up as the inconsistency doesn't seem like it would be intentional.

---

As a side note to anyone else coming across this, Jest can be configured to map the default `navaid` import to the `.mjs` file:

```javascript
// jest.config.js

module.exports = {
	// ...

	moduleNameMapper: {
		// use the navaid.mjs file when Jest finds `import navaid from "navaid"`
		"^navaid$": "<rootDir>/node_modules/navaid/dist/navaid.mjs",
	},

	transform: {
		// transform .mjs files with babel
		"^.+\\.m?js$": "babel-jest",
	},

	// ...
}
```

**Comment by lukeed** [comment]
Hey, this would have to do with your Jest configuration/mapping. I'm not sure what exactly, but something is definitely off as [there is no named CommonJS export](https://www.runpkg.com/?navaid@1.1.1/dist/navaid.js#27)

**Comment by larrybotha** [comment]
oh whoops, that is a default export :P 

Um, yeah, then there's something that I don't understand about Node / Jest internals that results in an `undefined` import for `navaid.js`. It may very well be some weird Babel transformation causing the issue, but I wouldn't think so - it's just importing commonJs O.o

Oh well, my config addresses whatever is going on, and `navaid` has consistent exports, so I'll close this.

Thanks for the quick response, @lukeed! Keep kicking ass :)
