### ISSUE TITLE
404 flashes on page refresh

### ISSUE THREAD

**Issue by jimafisk** [lukeed/navaid#31]
Hi @lukeed thanks for your work on this router! I'm having some trouble with 404 page not found handling and was wondering if you could point me in the right direction. Whenever I do a <kbd>Ctrl</kbd>+`r` to reload the page I see the 404 page flicker before loading the correct page (sometimes it doesn't reach the correct page and just loads the 404). Here are some project details in case it's helpful:

- I have static HTML fallbacks for each page that hydrate into svelte components
- The static HTML paths are in the format `/about/index.html` so I match the urls with trailing slashes and redirect them to the same page but without the slash in the spa (e.g. `/about`)
- I dynamically create the routes using a data source (`nodes.js`)

<details>
<summary>Click to see router code</summary>

```html
<Html {route} {node} {allNodes} />

<script>
  import Navaid from 'navaid';
  import nodes from './nodes.js';
  import Html from '../global/html.svelte';

  let route, node, allNodes;

  const getNode = (uri, trailingSlash = "") => {
    return nodes.find(node => node.path + trailingSlash == uri);
  }

  let uri = location.pathname;
  node = getNode(uri);
  if (node === undefined) {
    node = getNode(uri, "/");
  }
  allNodes = nodes;

  function draw(m) {
    node = getNode(uri);
    if (node === undefined) {
      // Create a placeholder node so props are complete
      node = {
        "path": "/404",
        "type": "404",
        "filename": "404.json",
        "fields": {}
      }
    }
    route = m.default;
    window.scrollTo(0, 0);
  }

  function track(obj) {
    uri = obj.state || obj.uri;
  }

  addEventListener('replacestate', track);
  addEventListener('pushstate', track);
  addEventListener('popstate', track);

  const router = Navaid('/', () => import('../content/404.js').then(draw));

  allNodes.forEach(node => {
    router.on(node.path, () => {
      // Check if the url visited ends in a trailing slash (besides the homepage).
      if (uri.length > 1 && uri.slice(-1) == "/") {
        // Redirect to the same path without the trailing slash.
        router.route(node.path, false);
      } else {
        import('../content/' + node.type + '.js').then(draw);
      }
    }).listen();

  });

</script>
```

</details>

Thanks!

**Comment by lukeed** [comment]
Hi there,

You are calling `.listen()` **inside** your `allNodes.forEach` loop. I imagine something like this is happening:

```js
// Assume we're on home page ("/")

allNodes = [
  { path: '/foobar' },
  { path: '/hello' }
  // ...
]

allNodes.forEach(node => {
  router.on(node.path, ...);
  // Router ONLY has "/foobar" right now
  router.listen(); 
  // ^ AKA: "please match {{ current location }} against all known routes ("/foobar")
  // -> NOT a match, load 404
})
```

Does that sound about right?

**Comment by lukeed** [comment]
Also, not sure if you've seen it, but I have a Navaid + Svelte demo [here](https://github.com/lukeed/svelte-demo/blob/master/src/components/App.svelte)

**Comment by jimafisk** [comment]
Ah yes of course, you are 100% correct! Thanks so much for the quick response, it's working beautifully now.

Also thanks for the demo link, I was using that as a model with some modifications to fit my app. Here's a link in case you're interested in seeing different places that are using Navaid in action: https://github.com/plentico/plenti

**Comment by lukeed** [comment]
Cool! Glad it's working :)

That looks like an interesting project. Love seeing cross-language use cases. I'll circle back in a few weeks to give it a spin~!

**Comment by jimafisk** [comment]
Awesome thanks!
