### ISSUE TITLE
svelte + snowpack + navaid

### ISSUE THREAD

**Issue by anonimusprogramus** [lukeed/navaid#35]
This is not a real issue, I just want to share that navaid works!
(after finding atm other routers having problem with snowpack)

Hope this helps :smiley: 

In `stores.js`

```javascript
import { writable } from 'svelte/store'

export const component = writable(null)
```

In `routes.js`

```javascript
import navaid from 'navaid'
import { component } from './stores'

import Dashboard from './views/Dashboard.svelte'
import NotFound from './views/NotFound.svelte'

let router = navaid()

router.on('/', () => component.set(Dashboard))
router.on('*', () => component.set(NotFound))

export default router
```

In `App.svelte`

```javascript
<script>
  import { component } from './stores'
</script>

<svelte:component this="{$component}" />
```

**Comment by lukeed** [comment]
Cool! 🎉

You can also use the [`on404`](https://github.com/lukeed/navaid#on404) parameter instead of a `*` route. Just an FYI but is effectively the same thing.

Closing this, but thank you for sharing :)

**Comment by aldomendez** [comment]
Hi, I has stuck unable to make it display anything, and found that adding to `main.js`:


```js
import router from './routes'

router.listen()
```

was the cherry on the cake that makes this thing fly.

Thank you so much for the head start, I was looking for a navigation solution for svelte.
