### ISSUE TITLE
Using for the first time with Svelte.

### ISSUE THREAD

**Issue by frederikhors** [lukeed/navaid#4]
I'm trying for the first time Svelte and wanna use the amazing Navaid.

I'm trying it here: https://codesandbox.io/s/n1kll9z3ll.

Two questions:

1. if you click on a link in <Navbar/> nothing works. Why?

2. how to render Home.svelte in <App/>?

**Comment by lukeed** [comment]
Hey, so you aren't telling Svelte where it should put child content. Whether this is a slot or component binding, you have neither. As defined, your app will always only be showing "App Component" on all pages. 

Your (1) and (2) are the same problem.

I'd recommend you take a look thru [here](https://github.com/lukeed/svelte-demo/blob/master/src/components/App.svelte), which is a complete Svelte 3.x demo with Navaid.

Hope that helps~!
