### ISSUE TITLE
Any react or preact example?

### ISSUE THREAD

**Issue by kethan** [lukeed/navaid#42]
Can anyone share me a snippet?

**Comment by kethan** [comment]
How do I return component inside on function. Using state? Any help appreciated

**Comment by lukeed** [comment]
Here's a [little codesandbox](https://codesandbox.io/s/hopeful-hertz-h2wj9) I put together for you.

You can do anything, really. Navaid is a "vanilla" library, so as long as you have reference to a DOM node somewhere (`$main` in this case), you can render/update views however you want. The second piece is to `.listen()` when you know the App is ready. In a Preact/React world this would be `componentDidMount` or whatever the effect/hooks equivalent is.

Hope that helps!

**Comment by kethan** [comment]
Oh wow, that was not like a snippet it was like the small application you have given. Thanks I will take sometime to understand and implement it. I will have to learn how hydrate works. I appreciate your help.

**Comment by lukeed** [comment]
No problem :)

Here's [`preact.hydrate`](https://preactjs.com/guide/v10/api-reference/#hydrate) docs, but it's common to all React-like libraries. It's basically the same thing as `preact.render`, but it tries to reuse the existing HTML on the page, whereas `render()` would jump immediately to replacing everything w/ a new copy

**Comment by kethan** [comment]
I am happy with this solution. The only thing I need is lazy load components. I am unable to achieve that.

**Comment by lukeed** [comment]
You can, you just need to involve the bundler that you're using.

The example i gave used:

```js
const HOME = import("/src/pages/Home.jsx");
const LIST = import("/src/pages/List.jsx");
const ITEM = import("/src/pages/Item.jsx");
const OOPS = import("/src/pages/Oops.jsx");
```

Which, technically, are all lazy-loaded chunks – they just all start loading initially. 
Codesandbox did some weird pathing thing where this had to be done, but generally your handlers would look something like this:

```js
Navaid("/", on404)
  .on("/", () => run(() => import("/src/pages/Home.jsx")))
  .on("/list", () => run(() => import("/src/pages/List.jsx")))
   // ...
```

I mention bundler involvement because you may have to add some aliasing/configuration so that the `src/pages/Home.jsx` paths resolve correctly.

**Comment by kethan** [comment]
Very helpful thank you. I am using Vitejs which does automatic chunk splitting I guess.
