### ISSUE TITLE
Hi, a small question

### ISSUE THREAD

**Issue by YUFENGWANG** [lukeed/navaid#48]
It's a tiny great lib, but i have a question.
Does browser native support 
![image](https://user-images.githubusercontent.com/12859005/156115624-5f32834c-b1cc-4c02-a9ee-1276d349d8d1.png)
these two events? I can't find it  
thank you !

**Comment by lukeed** [comment]
Hey, thanks 

no they’re created by this library and are used as normalization across all browsers by how it’s done: https://github.com/lukeed/navaid/blob/b2b105abcf6c465621710c55e66117bf8f020b68/src/index.js#L85
