### ISSUE TITLE
Memory leak, sort of. Events get called multiple times

### ISSUE THREAD

**Issue by jacwright** [lukeed/navaid#8]
At the beginning of `listen` you wrap the history's `pushState` and `replaceState` so they dispatch a function when called. The problem is, if you call unlisten and listen again, or have multiple instances of `navaid` in the page, those wrapped functions get wrapped over and over and dispatch multiple events each page change.

https://github.com/lukeed/navaid/blob/master/src/index.js#L43

**Comment by frederikhors** [comment]
Same problem here. @lukeed this seems serious.

**Comment by lukeed** [comment]
RE: memory leak for `unlisten() -> listen()` is definitely a problem and will be fixed regardless.

---

There's not really a good way to handle multiple routers within the same page... currently. 
But what do you guys think about this for handling multiple routers in a page?

```js
var main = (
  navaid()
    .on('/', () => console.log('Home'))
    .on('/about', () => console.log('About'))
);

var items = (
  navaid()
    .on('/items/', () => console.log('Items Home'))
    .on('/items/:title', x => console.log('Item: ', x.title))
);

main.use(items);
main.listen();
```

I already have this built, and it seems to be the only _sane_ way to juggle multiple routers on a page. It's currently `867B` which is `+35B`.

As for actual routing, it will look at the `main` routes first and then the sub-routers' routes in the order that they were defined (via `use()` hookups).

**Comment by lukeed** [comment]
Fixed the memory leak. We can discuss multiple routers separately: (will link)
