### ISSUE TITLE
Query params

### ISSUE THREAD

**Issue by jacwright** [lukeed/navaid#9]
Would you be open to a contribution that supported query params?

It would be removing the query string from the end of the `uri` sent to `run` before looking for matching routes, then splitting they query string into its key-value pairs and sending those as a second parameter to the route function. E.g.

```js
router.on('/users', (params, query) => {
  // use query params to sort, filter, etc the user list.
  const { sort, filter, limit } = query;
  ...
}
```

**Comment by lukeed** [comment]
I don't think so, no. The query prams are easily accessed on `location` from anywhere and they have no effect on routing/matching. 

Unlike pathnames and `base`, there'd be nothing thru navaid that says you want to only limit/key `sort` sometimes but not others. 

All that stuff (parsing) happens inside the route handler, and only once the pathname has been matching the first place... And should only happen if you wanted to happen.

```js
import { decode } from 'qss';

navaid()
  .on('/users/:id?', params => {
    console.log('user id, if any', params.id);
    const { sort, filter, limit } = decode(location.search.substring(1));
    // ... Or use UURLSearchParams if you want
    // It's your choice, as it should be
  })
```

**Comment by jacwright** [comment]
Adding a query string currently breaks the path matching, so to use it navaid needs to at least drop it from `uri` before matching against routes. I the decoding should happen in the handler.

**Comment by lukeed** [comment]
Thanks for the report @jacwright 👍
